name: Unit Tests & deploy library
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.13"]
    services:
      redis:
        #image: redis
        # use the redis-stack-server without redis-insight
        # we use our own redis version which turns off the protected-mode
        image: svabra/redis-stack-server
        ports:
          - 6379:6379
        options: >-
          --entrypoint "redis-server --protected-mode no"
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5     
    steps:
    - uses: actions/checkout@v3    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip          
        pip install pytest redis
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Running all PyTests
      env:
        REDIS_OM_URL: redis://localhost:6379/0
      run: |
        pytest -s -vv
